export const FRIENDS_UPDATE_STATUS_TYPE = {
  ACCEPTED: 'ACCEPTED',
  REJECT: 'REJECT',
  REMOVE: 'REMOVE',
  ADD: 'ADD',
  SENT: 'SENT',
  CANCEL: 'CANCEL',
  RECEIVED: 'RECEIVED',
  NOT_FRIEND: 'NOT_FRIEND',
  ACCEPT: 'ACCEPT',
};
